spring.application.name=car-rent
server.port=8080
spring.datasource.url=${DB_CONNECT_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=QWERTYUIOPASDFGHJKLZXCVBNMqwertyuiopasdfghjklzxcvbnm1234==
jwt.expiration=3600000

stripe.api-key=sk_test_51RYUH1QserlTiJ9xmCRFc63qjzCXjzXgESiQ2qhdI70pToVPuIvXWIpbFvY5UNxYu3n9ngHtKerUHjWdfF6wkNxP00CDFMCboE
stripe.webhook-secret=whsec_aaa34f747b8301db3705bdef303863192ced2fe20a9b631f4c2af6e6c1b56be0